# Generated by Django 3.2.16 on 2024-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20241210_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано'),
        ),
    ]
