# Generated by Django 3.2.16 on 2024-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static_dev/img/', verbose_name='Изображение'),
        ),
    ]
