# Generated by Django 3.2.16 on 2025-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='distance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расстояние'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='region',
            field=models.CharField(blank=True, max_length=30, verbose_name='Регион'),
        ),
    ]
